version: "3.5"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=clientes
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql    
    command: postgres -c max_connections=500 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "245MB"
    healthcheck:
      test: ["CMD", "pg_isready", "--database", "clientes", "--username", "admin"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
      start_interval: 1s      

  api_1:
    container_name: api_1
    image: gustavofbreunig/ddd-rinha-2023-q1:latest
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    ports:
      - "8081:8080"      
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "130MB"

  api_2:
    container_name: api_2
    image: gustavofbreunig/ddd-rinha-2023-q1:latest
    environment:
      - DB_HOSTNAME=db    
    depends_on:
      - db
    ports:
      - "8082:8080"        
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "130MB"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_1
      - api_2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "45MB"    

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
