version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=clientes
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"
    healthcheck:
      test: ["CMD", "pg_isready", "--database", "clientes", "--username", "admin"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
      start_interval: 1s

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
