version: "3.5"

services:
  api01:
    hostname: api01
    image: gustavofbreunig/ddd-rinha-2023-q1:latest
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8080"      
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "170MB"

  api02:
    hostname: api02
    image: gustavofbreunig/ddd-rinha-2023-q1:latest
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"        
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "170MB"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=clientes
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.config_file
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.config_file
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"    

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
